config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, only: [:show]
  root 'tweets#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet, optional: true
  belongs_to :user, optional: true

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  has_many :tweets, dependent: :destroy 
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 }
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      tweet = Tweet.find(params[:tweet_id])
      comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end
    def destroy
        Comment.find(params[:id]).destroy
        redirect_to tweets_path
      end
    
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweets = Tweet.all
   
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
  end
end


  

def show
  @tweet = Tweet.find(params[:id])
  @comments = @tweet.comments
  @comment = Comment.new
end 

def edit
  @tweet = Tweet.find(params[:id])
end

def update
  tweet = Tweet.find(params[:id])
  if tweet.update(tweet_params)
    redirect_to :action => "show", :id => tweet.id
  else
    redirect_to :action => "new"
  end
end

def destroy
tweet = Tweet.find(params[:id])
tweet.destroy
redirect_to action: :index
end
 
  private
def tweet_params
  params.require(:tweet).permit(:about, :name, :address, :image)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kesennuma</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <h1>ここからここまで<br>気仙沼</h1>
    <div class="header-list">
    <ul>
      <li><%= link_to "ホーム", tweets_path %></li>
      <li><%= link_to "新規投稿",new_tweet_path%></li>
    </ul>
    </div>
 </header>
    <%= yield %>
  </body>
</html>




<footer>
<p>Copyright © Atsuka Oyama All Rights Reserved..</p>
</footer>

app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

<p>Find me in app/views/tweets/new.html.erb</p>
<h3>編集Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :about %>
    <%= f.text_field :about, :size => 140 %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %> 
  </div>
  <div class="field">
  <%= f.label :address %>
  <%= f.text_field :address, :size => 140 %>
</div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/index.html.erb
<h3>投稿一覧</h3>
<%= link_to "新規投稿へ", new_tweet_path %>
<% if user_signed_in? %>
<%= link_to "マイページへ", user_path(current_user.id) %>　
<% end %>


<div class="tweet-container">
      <% @tweets.each do |t| %>
        <div class=“tweet”>
        <%= t.user.email %>
          <%= t.name %>
          <%= t.address %>
          <%= t.about %>
          <%= image_tag t.image_url, size: "250x200" if t.image? %>
          <%= t.created_at %>
          <%= link_to "詳細へ", tweet_path(t.id) %>
          <% if user_signed_in? && current_user.id == t.user_id %>
          <%= link_to "編集する", edit_tweet_path(t.id) %>
        <%= button_to "削除する", tweet_path(t.id), method: :delete %>
        <% end %>

          <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                  <p>いいねを取り消す</p><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                  <p>いいね</p><%= t.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <p>いいねの数 = </p><%= t.likes.count %>
        <% end %>
        </div>
  <% end %>
 
</div>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :about %>
    <%= f.text_field :about, :size => 140 %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %> 
  </div>
  <div class="field">
  <%= f.label :address %>
  <%= f.text_field :address, :size => 140 %>
</div>
<div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>
<% if user_signed_in? %>
<% if current_user.already_liked?(@tweet) %>
    <%= link_to tweet_like_path(@tweet), method: :delete do %>
       <p>いいねを取り消す</p><%= @tweet.likes.count %>
    <% end %>
<% else %>
    <%= link_to tweet_likes_path(@tweet), method: :post do %>
       <p>いいね</p><%= @tweet.likes.count %>
    <% end %>
<% end %>
<% else %>
<p>いいねの数 = </p><%= @tweet.likes.count %>
<% end %>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
      <p><%=link_to "削除", comment_path(c.id), method: :delete %></p>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %><br>
  <%= t.about %><br>
  <%= t.address %><br>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.about %>
  <%= t.address %><br>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
<% end %>
<!-- ここまで-->

<%= link_to "Tweet一覧に戻る", tweets_path %>